### ISSUE TITLE
tracing downstream services

### ISSUE THREAD

**Issue by tejasnomulwar** [smoketurner/dropwizard-zipkin#10]
Hi,
Does this library support tracing downstream services? As mentioned in the zipkin docs:

> If the service calls out to a downstream service a new span is created as a child of the former span. It is identified by the same trace id, a new span id, and the parent id is set to the span id of the previous span. 
Note This process must be repeated if the service makes multiple downstream calls. That is each subsequent span will have the same trace id and parent id, but a new and different span id.

Does this work out of the box or do I have to make some changes to my code?

Thanks.

**Comment by jplock** [comment]
If every service is using `dropwizard-zipkin` and you are building your clients out of the client builders within this module, then everything should be wired up correctly.  If you are working with other client implementations or services, then you have to set up the tracing manually.

**Comment by tejasnomulwar** [comment]
Ok. Great. Thanks.
