### ISSUE TITLE
AbstractZipkinFactory should allow configurable Sampler

### ISSUE THREAD

**Issue by spudone** [smoketurner/dropwizard-zipkin#13]
buildBrave in AbstractZipkinFactory currently calls Sampler.create(sampleRate), which uses CountingSampler.

This is insufficient for high traffic sites as it puts a floor of .01 (1%) on the sampleRate.  An option to pass in a specific Sampler implementation, rather than the sample rate alone, would be useful.  For example, BoundarySampler allows more granularity.

**Comment by jplock** [comment]
Fixed in `1.0.3-2`

**Comment by Jubobs** [comment]
How do you specify which type of `Sampler` to use? Can it be done in the yml config file?
