### ISSUE TITLE
Support @Priority annotation

### ISSUE THREAD

**Issue by janolaveide** [smoketurner/dropwizard-zipkin#2]
I have a chain of filters in addition to the brave filters in my DW servers. These also connect to other services (for authorization etc). In order to get the timing right, I would like the Brave request filter to  be the first  in the request processing chain, and the response filter to be the last. For the client filters, I achive this by subclassing the brave filters, supplying a @Priority annotation in the subclass.  Not sure what would be the best way of supporting this in the Zipkin bundle ? Maybe a couple of extra arguments to the build method, where the class names of the subclasses can be provided ?

**Comment by jplock** [comment]
I think we should submit a PR to the brave project

**Comment by janolaveide** [comment]
Agreed,  it is probably better.  I can think of no use cases where one would not want the request filter to execute first, and the response filter to execute last, so a @Priority(0) is probably always correct.

**Comment by janolaveide** [comment]
https://github.com/openzipkin/brave/issues/134
Not much interest so far....

**Comment by jplock** [comment]
@janolaveide Our fix was released in Brave 3.5.0 and I just pushed up `dropwizard-zipkin` v0.9.2-3 to Maven Central which includes that release.  If it looks good with you, we should be able to close out this issue.
