### ISSUE TITLE
cannot change serviceName in zipkinClient configuration

### ISSUE THREAD

**Issue by musicccman** [smoketurner/dropwizard-zipkin#20]
serviceName is required for zipkinClient  configuration. When I tried to change serviceName in zipkin-example configuration (hello-world.yml), this name wasn't changed in application. I tried to debug this issue and noticed that this value was overrided  at runtime  with Environment.name value.  (We defined this value when overrided getName() method in zipkin-example HelloWorldApplication class)

**Comment by jplock** [comment]
Thanks, probably similar fix to what we did in https://github.com/smoketurner/dropwizard-consul/pull/29

**Comment by musicccman** [comment]
Great, Thank you. I'd like to recommend you to add serviceName to main zipkin properties of hello-world.yml (now zipkin-client has this properties, but not main zipkin config)
