### ISSUE TITLE
Brave 4

### ISSUE THREAD

**Issue by ghost** [smoketurner/dropwizard-zipkin#22]
Disclaimer ; Still learing this, so I may be totally off the mark here. 
But from this link  I understand that  one a can get from brave4 to brave3 through an adapter:
https://groups.google.com/forum/#!topic/zipkin-user/TfRHcJjKGzk

Would it not be better, moving forward, to have the ZipkinFactory#build method  of this bundle return a Tracer and not a Brave object ?

**Comment by jplock** [comment]
I've been watching the progress of Brave 4 and will be updating this adapter accordingly once it's finished.  I think it's almost done.

**Comment by buypass** [comment]
Great, it looks like Brave is on 4.2 now, so I am not  quite sure what you mean by "done". But good to know that this is on the drawing board, it will simplify stuff on my side.

**Comment by adriancole** [comment]
by done, there's new instrumentation code that takes advantage of the apis
added in Brave 4. This code is faster, smaller and more customizable!

**Comment by adriancole** [comment]
Brave 4.3 snapshot is out with the new http layer and code. Lemme know how
it feels in real life
