### ISSUE TITLE
LoggingZipkinFactory Missing

### ISSUE THREAD

**Issue by nheitz** [smoketurner/dropwizard-zipkin#24]
In the latest release (coupled with dropwizard 1.2.0), the class LoggingZipkinFactory is no longer present.  It is, however, still listed in META-INF/services as an available factory.  Is this meant to be replaced by ConsoleZipkinFactory, or is there a a separate issue?

**Comment by jplock** [comment]
doh, thanks. Yea logging factory no longer exists in later brave versions but I forgot to remove that reference.

**Comment by jplock** [comment]
Should be fixed in the latest release
