### ISSUE TITLE
support nested spans for nested method calls

### ISSUE THREAD

**Issue by shankhanildas** [smoketurner/dropwizard-zipkin#25]
Can this library be extended to send spans for nested method calls?

**Comment by jplock** [comment]
I’d accept a pull request for this.

**Comment by shankhanildas** [comment]
This would need to go aop based for a cleaner implementation. I could do with spring aop in my case. If we want to integrate with this library what is your thought?

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/blob/3bf0ebc0d16efb4d964ae1910c41cdd3411870dd/brave/src/test/java/brave/features/sampler/AspectJSamplerTest.java#L75
for an example of using brave for aspectj

feel free to raise an issue there for formalized aspectj support. I know
someone has one.

PS I owe some help on this repo, it is on my nag list to contribute.. sorry
I've not

**Comment by jplock** [comment]
I could definitely use some help with this library. zipkin has been changing too rapidly for me to keep up.

**Comment by adriancole** [comment]
@shankhanildas please suggest which route you'd like to take. if AOP, and there's an existing DW pattern, suggest away. I'll try to help

**Comment by shankhanildas** [comment]
Thanks @adriancole for the suggestions. I already did similar things as that of what you [mentioned](https://github.com/openzipkin/brave/blob/3bf0ebc0d16efb4d964ae1910c41cdd3411870dd/brave/src/test/java/brave/features/sampler/AspectJSamplerTest.java#L75) with dropwizard and spring and it's working fine.  Spring aop keeps the sanity aop implementation and for the time being it's taken care of. However, if you want to formalize the aop support from brave, do you have anything in mind? Thanks.

**Comment by jplock** [comment]
I would prefer not introducing any spring dependencies if we can avoid it.  My intention with this DW bundle was to keep it focused just on zipkin

**Comment by shankhanildas** [comment]
Yes, that's the exact reason I refrained from touching this implementation. However, if we want to send nested spans, aop would be the cleanest approach; but there is no point of introducing those at this layer, I agree. Not sure, what's the other way out.

**Comment by shankhanildas** [comment]
As said, currently my problem is solved. Was just thinking, if we can integrate in any way, rather than everyone left to their own aop implementations if there is a need to send nested spans.
