### ISSUE TITLE
Support per-operation sampling

### ISSUE THREAD

**Issue by xihw** [smoketurner/dropwizard-zipkin#38]
Brave provides a "HttpRuleSampler" for configuring per-operation sampling strategy. For example, health check requests are usually noisy and I want to exclude them out, and I can do 

httpTracingBuilder.serverSampler(HttpRuleSampler.newBuilder()
  .addRule(null, "/healthcheck", 0.0f)
  .build());

As mentioned here: https://github.com/openzipkin/brave/tree/master/instrumentation/http#sampling-policy

Looks like dropwizard-zipkin has not supported it yet. Can we add it ?

**Comment by adriancole** [comment]
I think a change like this or similar would allow arbitrary changes to
things like http sampler. HttpTracing can already be configured, but not
fine grained iiuc
https://github.com/spring-cloud/spring-cloud-sleuth/compare/6ce2df4c1ff48c2583187797941d77a5d7996470...cf8676ccfd5be341343253ffb12c96951789a096
