### ISSUE TITLE
Is trace id logging supported ?

### ISSUE THREAD

**Issue by xihw** [smoketurner/dropwizard-zipkin#40]
As I know, we can use one of the logging plugins from here
https://github.com/openzipkin/brave/tree/master/context

and configure log format like so
https://github.com/openzipkin/brave-webmvc-example/blob/master/webmvc4/src/main/resources/log4j2.properties#L5

to enable putting trace id into logs.

Does dropwizard-zipkin support it ?

**Comment by adriancole** [comment]
it looks like dropwizard uses logback https://www.dropwizard.io/1.0.4/docs/manual/configuration.html#logging
So, to support trace IDs in logs, you'd need brave-context-slf4j and this configured in the Tracing component used here (Tracing.builder.currentTraceContext with MDCCurrentTraceContext)

then in your dropwizard log appenders config, you'd add logFormat with a pattern similar to what's in the file you linked.
