### ISSUE TITLE
Can we upgrade to Brave 5.1.0 ?

### ISSUE THREAD

**Issue by xihw** [smoketurner/dropwizard-zipkin#44]
Currently there is a bug on handling http.route for async resources as mentioned here https://github.com/openzipkin/brave/issues/715. And They just fixed it in Brave 5.1.0 ! Can we upgrade to it ? @jplock

**Comment by adriancole** [comment]
finally it is synced to maven central!

**Comment by jplock** [comment]
I’ll try and upgrade to this and DW 1.3.3 tomorrow.

**Comment by jplock** [comment]
Just pushed 1.3.4-1 to Maven Central with Brave 5.1.0

**Comment by xihw** [comment]
Is it pushed? I cannot download it :)

**Comment by adriancole** [comment]
I see it in central now. wanna try?
