### ISSUE TITLE
Upgrade to brave 5.1.2 to fix scope bug

### ISSUE THREAD

**Issue by xihw** [smoketurner/dropwizard-zipkin#46]
I have a PR ready, https://github.com/smoketurner/dropwizard-zipkin/pull/45
This upgrade will fix this [issue](https://github.com/openzipkin/brave/issues/722)

Can you please merge it? Thanks!

**Comment by adriancole** [comment]
ps apologies about this bug. it was avoidable we didnt have good coverage
on async stuff.

**Comment by xihw** [comment]
Thank you @jplock. And can you release it ?

**Comment by jplock** [comment]
Maybe later tonight EST.

**Comment by jplock** [comment]
Just pushed v1.3.4-2 to Maven Central.
