### ISSUE TITLE
Submit Binary Annotation

### ISSUE THREAD

**Issue by rakeshkaundilya** [smoketurner/dropwizard-zipkin#6]
Hi all, 
I am having trouble submitting binary annotations in drowpwizard application.
I tried using following code in run method:
` 

```
    Brave brave = configuration.getZipkinFactory().build(environment);

    final Client client = new ZipkinClientBuilder(environment, brave).build(configuration.getZipkinClient());

    brave.serverSpanAnnotationSubmitter().submitBinaryAnnotation("Key_test","value_test");
    environment.jersey().register(new LearnDWResource(client));
`
```

**Comment by jplock** [comment]
I personally haven't used this functionality before.  Is `Key_test` suppose to be included on each span?

**Comment by rakeshkaundilya** [comment]
Yes. 
I am new to this project but the way this feature is mentioned, it should come under binaryAnnotations field. For example the `http.url` or `http.status_code` is present in span.
However I am not sure this is how it should be called to submit annotations.

**Comment by pengxiaofengzhongxiaodan** [comment]
I know why~! 
Did you solve it?

**Comment by rakeshkaundilya** [comment]
No, We made our own tool using the same idea.
