### ISSUE TITLE
Automatically call build from run

### ISSUE THREAD

**Issue by reftel** [smoketurner/dropwizard-zipkin#61]
Presently, the application is supposed to call `build` on the zipkin bundle from within its `run` method. That means that the zipkin bundle's `build` method gets called after the `run` methods of all other bundles have been called, so it's therefore not possible for them to access the `HttpTracing` instance from there. That makes it complicated to add tracing to requests made from bundles.
If the `run` method of the zipkin bundle would instead itself call `build`, and store the result in a field with a getter, then by adding the zipkin bundle first, and arranging to have the bundles that want to trace get a reference to the zipkin bundle, one could let those bundles ask for the `HttpTracing` instance from their `run` methods, and use that to configure their clients.

**Comment by jplock** [comment]
Mind submitting a pull request?

**Comment by reftel** [comment]
Sure! Will send a PR in the morning, CET.

**Comment by jplock** [comment]
Fixed in `v1.3.12-1`
