### ISSUE TITLE
Set Zipkin base path

### ISSUE THREAD

**Issue by pavolloffay** [smoketurner/dropwizard-zipkin#8]
Is it possible to set Zipkin base path url in the configuration?

**Comment by jplock** [comment]
@pavolloffay right now the only configuration is a host and port to send spans to.  I'm assuming this would only apply to the HTTP transport.  Would you like to submit a pull request to add this?

**Comment by adriancole** [comment]
fyi in spring-cloud-sleuth we use the property baseUrl to indicate the
prefix for /api/v1/spans
https://github.com/spring-cloud/spring-cloud-sleuth/blob/48f3f9783f277a795d0210399f0ea09b7f1a4e71/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinProperties.java#L30
