### ISSUE TITLE
Upgrade to Brave 5.9.2 to fix issue with read-only headers

### ISSUE THREAD

**Issue by msmsimondean** [smoketurner/dropwizard-zipkin#89]
Upgrade to Brave [5.9.2](https://github.com/openzipkin/brave/releases/tag/5.9.2) or later to bring in the fix for https://github.com/openzipkin/brave/issues/1045

[5.10.1](https://github.com/openzipkin/brave/releases/tag/5.10.1) is the latest version

**Comment by jcchavezs** [comment]
Ping @smoketurner

**Comment by jcchavezs** [comment]
Would you come up with a PR fixing this @msmsimondean ? cc @smoketurner

**Comment by jplock** [comment]
I'll try to release a new version later this week.

**Comment by koalalam** [comment]
What's the latest plan? Thank you.
