### ISSUE TITLE
Support passing a list of FinishedSpanHandler to Tracing.newBuilder()

### ISSUE THREAD

**Issue by msmsimondean** [smoketurner/dropwizard-zipkin#90]
Brave has a feature where you can extend [FinishedSpanHandler](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/handler/FinishedSpanHandler.java) and use it to customise spans.  It can be used for things like redaction of sensitive data in HTTP paths.

**Comment by jcchavezs** [comment]
Not a Java expert but I wonder how this could be achieved if FinishedSpanHandlers need construct arguments. I just had to face this myself and went for the option of creating my own `ZipkinBundle` implementation and I was about to open a PR for improving docs around that. Would that work for you @msmsimondean ?

**Comment by jplock** [comment]
Welcome to review a PR

**Comment by adriancole** [comment]
note: https://github.com/openzipkin/brave/pull/1148 will deprecated FinishedSpanHandler for SpanHandler and be released in the next couple days
